import random
import Splitter
import Gadget
import Joiner
import Solver



class Variable_encoding:
    def __init__(self, encoding=None, variables=None, variable_to_literal=None, literal_to_variable=None):
        if variables is not None:
            self.variables = variables
        else:
            self.variables = set([v for v in encoding.values() if v is not None])
        if variable_to_literal is not None:
            self.variable_to_literal = variable_to_literal
        else:
            variable_to_literal = {}
            for variable in self.variables:
                variable_to_literal[variable] = []
                for k, v in encoding.items():
                    if variable==v:
                        variable_to_literal[v].append(k)
            self.variable_to_literal = variable_to_literal
        if literal_to_variable is not None:
            self.literal_to_variable = literal_to_variable
        else:
            self.literal_to_variable = encoding



class SAT_solver:
    def __init__(self, file_path=None, clauses=None, N=None, splitter=None, gadget=None, joiner=None, solver=None, token=None, qubit_level=False):
        self.file_path = file_path    
        if file_path is not None:
            self.clauses, self.N = splitter.Parse_cnf_file(file_path)
            random.seed(901)
            for clause in self.clauses:
                random.shuffle(clause)
        else:
            self.clauses = clauses,
            self.N = N
        self.splitter = splitter
        self.gadget = gadget
        self.joiner = joiner
        self.solver = solver
        self.token = token
        self.qubit_level = qubit_level
    
    def Solve(self):
        if self.splitter is not None:
            self.subproblems = self.splitter.Split(self.clauses)
            if self.gadget is not None:
                Mappers = []
                for i, subproblem in enumerate(self.subproblems):
                    if len(self.gadget)==1:
                        Mappers.append(self.gadget[0].FillQ(subproblem)) #[Q, encoding]   
                    elif len(self.gadget)!=1 and len(self.subproblems)==len(self.gadget):
                        Mappers.append(self.gadget[i].FillQ(subproblem)) #[Q, encoding]
                    else:
                        raise Exception("Length of subproblems generated by Splitter does not match with length of Gadget array.")                  
                if self.joiner is not None:
                    if len(self.joiner)==1:
                        self.Q, Q_encoding = self.joiner[0].Join(Mappers)
                    elif len(self.joiner)!=1 and len(self.joiner)==len(self.gadget):
                        mappings = []
                        for i, Map in enumerate(Mappers):
                            Q, Q_encode = self.joiner[i].Join([Map])
                            mappings.append([Q, Q_encode])
                        self.Q, Q_encoding = Joiner.Bian().Join(mappings)
                    else:
                        raise Exception("Length of Mappers generated by Gadgets does not match with length of Joiner array.")
                    self.Q_encoding = Variable_encoding(encoding = Q_encoding)
                    if self.solver is not None:
                        self.response, self.embedding = self.solver.Solve(self.Q, self.token, self.qubit_level)
                        if self.qubit_level==False:
                            self.real_encoding = self.Q_encoding
                        else:
                            real_encoding = {}
                            for lit, var in Q_encoding.items():
                                for l, qubits in self.embedding.items():
                                    if lit==l:
                                        for q in qubits:
                                            real_encoding[q] = var
                            self.real_encoding = Variable_encoding(encoding = real_encoding)
                        self.o = self.solver.SAT_solution(self.real_encoding.variable_to_literal, self.clauses)


