import random
import Splitter
import Gadget
import Joiner
import Solver
import dimod
import subprocess


class Variable_encoding:
    def __init__(self, encoding=None, variables=None, variable_to_literal=None, literal_to_variable=None):
        if variables is not None:
            self.variables = variables
        else:
            self.variables = set([v for v in encoding.values() if v is not None])
        if variable_to_literal is not None:
            self.variable_to_literal = variable_to_literal
        else:
            variable_to_literal = {}
            for variable in self.variables:
                variable_to_literal[variable] = []
                for k, v in encoding.items():
                    if variable==v:
                        variable_to_literal[v].append(k)
            self.variable_to_literal = variable_to_literal
        if literal_to_variable is not None:
            self.literal_to_variable = literal_to_variable
        else:
            self.literal_to_variable = encoding



class SAT_solver:
    def __init__(self, instance=None, file_path=None, splitter=None, gadget=None, joiner=None, solver=None, token=None, qubit_level=False):
        if instance is not None:
            self.clauses = instance
            self.N = max([abs(v) for c in self.clauses for v in c])
            p = f"c generated problem\np cnf {self.N} {len(self.clauses)}\n"
            for c in self.clauses:
                for lit in c:
                    p += str(lit) + " "
                p += "0\n"
            self.file_path = f"../exp/eBeyond/Problems_SAT_solver/p{self.N}.cnf"
            with open(self.file_path,"w") as f:
                f.write(p)
        if file_path is not None:
            self.file_path = file_path  
            self.clauses, self.N = splitter.Parse_cnf_file(file_path)
            random.seed(901)
            for clause in self.clauses:
                random.shuffle(clause)
        self.splitter = splitter
        self.gadget = gadget
        self.joiner = joiner
        self.solver = solver
        self.token = token
        self.qubit_level = qubit_level
    
    def Solve(self):
        if self.splitter is not None:
            self.subproblems = self.splitter.Split(self.clauses)
            if self.gadget is not None:
                Mappers = []
                for i, subproblem in enumerate(self.subproblems):
                    if len(self.gadget)==1:
                        Mappers.append(self.gadget[0].FillQ(subproblem)) #[Q, encoding]   
                    elif len(self.gadget)!=1 and len(self.subproblems)==len(self.gadget):
                        Mappers.append(self.gadget[i].FillQ(subproblem)) #[Q, encoding]
                    else:
                        raise Exception("Length of subproblems generated by Splitter does not match with length of Gadget array.")                  
                if self.joiner is not None:
                    if len(self.joiner)==1:
                        self.Q, Q_encoding = self.joiner[0].Join(Mappers)
                    elif len(self.joiner)!=1 and len(self.joiner)==len(self.gadget):
                        mappings = []
                        for i, Map in enumerate(Mappers):
                            Q, Q_encode = self.joiner[i].Join([Map])
                            mappings.append([Q, Q_encode])
                        self.Q, Q_encoding = Joiner.Bian().Join(mappings)
                    else:
                        raise Exception("Length of Mappers generated by Gadgets does not match with length of Joiner array.")
                    self.Q_encoding = Variable_encoding(encoding = Q_encoding)
                    if self.solver is not None:
                        self.response, self.embedding = self.solver.Solve(self.Q, self.token, self.qubit_level)
                        if self.qubit_level==False:
                            self.real_encoding = self.Q_encoding
                        else:
                            real_encoding = {}
                            for lit, var in Q_encoding.items():
                                for l, qubits in self.embedding.items():
                                    if lit==l:
                                        for q in qubits:
                                            real_encoding[q] = var
                            self.real_encoding = Variable_encoding(encoding = real_encoding)
                        self.o = self.solver.SAT_solution(self.real_encoding.variable_to_literal, self.clauses)
                        
                        #Find optimum solution with exact classic solver
                        command = ["./../src/maxsatz", self.file_path]
                        exact_response = subprocess.run(command, capture_output=True)
                        for l in reversed(exact_response.stdout.decode('utf-8').splitlines()):
                            if l.split()[0] == 'o':
                                self.exact_o = int(l.split()[1])
                                break


    def print_QUBO(self, Q=None, encoding=None):
        if Q is None or encoding is None:
            print("Printing the final QUBO:\n")
            Q = self.Q
            encoding = self.Q_encoding.literal_to_variable
        
        qubo_vars = sorted(list(set(sum(Q.keys(), ()))))
        # Print the header row
        auxiliar = max([q_var for q_var, var in encoding.items() if var!=None])
        variable_labels = {abs(q_var): (f"x{abs(var)}" if var is not None else f"b{q_var-auxiliar}") for q_var, var in encoding.items()}
        
        header_row = ["QUBO"] + [variable_labels[k] for k in qubo_vars]
        print("{:<8}".format(header_row[0]), " ".join("{:>7}".format(var) for var in header_row[1:]))

        # Print the QUBO matrix rows
        for i in qubo_vars:
            i_idx = qubo_vars.index(i)
            
            print("{:<8}".format(f"Var {i}"), end=" ")

            for j in qubo_vars:
                if  qubo_vars.index(j) >= i_idx:
                    print("{:>7}".format(Q.get((i, j), 0)), end=" ")
                else:
                    print("{:>7}".format(0), end=" ")
            print("")

    def print_ISING(self, Q=None, encoding=None):
        if Q is None or encoding is None:
            print("Printing the final Ising matrix:\n")
            Q = self.Q
            encoding = self.Q_encoding.literal_to_variable
        h, J = dimod.qubo_to_ising(Q)[:2]
        matrix = {}
        for key, val in h.items():
            matrix[(key, key)] = val
        for key, val in J.items():
            matrix[key] = val
        Q = matrix
        
        qubo_vars = sorted(list(set(sum(Q.keys(), ()))))
        # Print the header row
        auxiliar = max([q_var for q_var, var in encoding.items() if var!=None])
        variable_labels = {abs(q_var): (f"x{abs(var)}" if var is not None else f"b{q_var-auxiliar}") for q_var, var in encoding.items()}
        
        header_row = ["ISING"] + [variable_labels[k] for k in qubo_vars]
        print("{:<8}".format(header_row[0]), " ".join("{:>7}".format(var) for var in header_row[1:]))

        # Print the QUBO matrix rows
        for i in qubo_vars:
            i_idx = qubo_vars.index(i)
            
            print("{:<8}".format(variable_labels[i]), end=" ")

            for j in qubo_vars:
                if  qubo_vars.index(j) >= i_idx:
                    print("{:>7}".format(Q.get((i, j), 0)), end=" ")
                else:
                    print("{:>7}".format(0), end=" ")
            print("")